<?php
include"k.php";
$id_pasien=$_POST['id_pasien'];
$nama=$_POST['nama'];
$tanggal_lahir=$_POST['tanggal_lahir'];
$jenis_kelamin=$_POST['jenis_kelamin'];
$alamat=$_POST['alamat'];
$no_telepon=$_POST['no_telepon'];
?>